---
- id: prevent-debug-markers
  name: Prevent XXX marker-comments
  description: Prevents lines containing '# XXX' to be committed
  entry: check-for-markers
  args:
    - "--pattern"
    - '# XXX'
  language: python
  types: [text]
