---
version: "3.3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/app/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

# vim: set ts=2 sw=2 :
